# Generated by Django 3.1 on 2020-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
