# Generated by Django 3.1 on 2020-08-28 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_checks_mealstoorder_order_servicepercentage_status_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='tableid',
        ),
        migrations.RemoveField(
            model_name='checks',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='checks',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='core.order'),
        ),
        migrations.AddField(
            model_name='checks',
            name='servicefee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicefee', to='core.servicepercentage'),
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealstoorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='core.order'),
        ),
    ]
