# Generated by Django 3.1 on 2020-08-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200828_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
        migrations.AlterField(
            model_name='mealstoorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.order'),
        ),
    ]
