# Generated by Django 3.1 on 2020-08-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200828_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='core.order'),
        ),
    ]
