# Generated by Django 3.1 on 2020-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200828_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
