# Generated by Django 3.1 on 2020-09-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200828_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealstoorder',
            name='count',
        ),
        migrations.RemoveField(
            model_name='mealstoorder',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealstoorder',
            name='order',
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='ordid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order1', to='core.order'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
        migrations.CreateModel(
            name='OrderedMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
