# Generated by Django 3.1 on 2020-09-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200904_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='servicefee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicepercentage'),
        ),
    ]
