# Generated by Django 3.1 on 2020-09-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200904_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealstoorder',
            name='ordid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals1', to='core.order'),
        ),
    ]
