# Generated by Django 3.1 on 2020-09-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_orderedmeals_mealstoorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waiterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
